// Created by Crowbar 0.71

$modelname "ARC9_rkArensal\bullet\9x19_empty_case.mdl"

$bodygroup "body"
{
	studio "9x19_case.smd"
}

$surfaceprop "default"

$contents "solid"

$illumposition 0 -1.795 1.118

$cdmaterials "models\ARC9_rkArensal\bullets\"

$cbox 0 0 0 0 0 0

$bbox -3.081 -1.119 -2.705 6.808 1.119 5.056

$hboxset "default"


$sequence "idle" {
        "anims\idle.smd" 
		fps 30
        snap
}
